### PR TITLE
Lazily evaluate variables

### LINKED ISSUE #197: Variables in arguments should be lazily evaluated
Variable values are substituted into commands by the `Gitsh::Transformer` as part of the parsing process. The result is that a `Gitsh::Command::Tree::*`—which composes two or more commands—doesn't work as expected when the LHS modified a variable that is used on the RHS.

Lazily evaluating argument values as part of the `Gitsh::Command::*#execute` method should solve this problem.

The expected behaviour is:

```
% :set x "1"
% :set x "2"; :echo $x
2
% :echo $x
2
```

The actual behaviour is:

```
% :set x "1"
% :set x "2"; :echo $x
1
% :echo $x
2
```

### PR DESCRIPTION
**Pull request by georgebrock**
Originally, gitsh would replace a variable with its value when transforming a command's AST into a command object. This made it impossible to write and then read a variable in the same command, e.g. with `:set x 1 && :echo $x`

Fixes #197

### CODE REVIEW

**Comment by mike-burns** [comment]
I like the elegance.

This is repeated, which is fine:

    args.map { |arg| arg.value(env) }

But it makes me wonder whether `env` should just know about `args`, or whether there should be an object that combines `env` and `args`.

**Comment by georgebrock** [comment]
Thanks!

I was considering a `Gitsh::ArgumentList` to wrap up the conversion from arguments to values. I'll give that a go and see if it improves things.

**Comment by georgebrock** [comment]
@mike-burns Paired with @sarony to add an `ArgumentList` class. Ready for another review.

File: lib/gitsh/argument_list.rb [hunk 1]
```diff
@@ -0,0 +1,21 @@
+module Gitsh
+  class ArgumentList
+    def initialize(args)
+      @args = args
+    end
+
+    def length
+      args.length
+    end
```
Comment (mike-burns) [inline lib/gitsh/argument_list.rb]: Where is `#length` used? The only place I see it in this PR, aside from the unit tests, are in `ArgumentBuilder::combined_arguments` -- but that's for an Array created in the initializer, not for an ArgumentList.

**Comment by mike-burns** [comment]
I like that new object. Just one question around `ArgumentList#length`; if I'm misreading something then it's good to merge.

File: lib/gitsh/argument_list.rb (hunk 1 above)
Comment (georgebrock) [inline lib/gitsh/argument_list.rb]: It's used by the command classes to verify that their argument lists contain the correct number of arguments (e.g. [internal_command.rb:65](https://github.com/thoughtbot/gitsh/blob/5136aa62b1c2c6fd233bd97cac760b45de7326af/lib/gitsh/commands/internal_command.rb#L65)).

**Comment by mike-burns** [comment]
Cool, looks good to merge.

**Comment by georgebrock** [comment]
Thanks for the review.
