### PR TITLE
Raise UnsetVariableError for magic variables.

### LINKED ISSUE #230: gitsh crashes when referencing $_prior does not exist
Here's the sequence of commands I performed to encounter the error:

```
> gitsh
checkout -b feature-branch
checkout master
branch -d $_prior
branch -d $_prior
```

And here's a simplified case:

```
> gitsh
!echo $_prior
```

### What happened

gitsh printed the following message and exited:

```
gitsh: Error: no implicit conversion of nil into String
```

### What I expected to happen

I expected gitsh to do one of the following, and continue accepting commands:

- print error about the variable not existing
- run the command with an empty value, and let errors bubble up

### PR DESCRIPTION
**Pull request by georgebrock**
The magic variables that gitsh provides all depend on certain state, e.g. the `$_merge_base` variable is only applicable during a merge.

This commit brings magic variables into line with regular user-defined variables, but raising an `UnsetVariableError` if they aren't currently set, i.e. if the state from which the variable derives its value doesn't exist.

Fixes #230

### CODE REVIEW

**Comment by teoljungberg** [comment]
One testing-question/recomendation. Besides that, merge at your descretion

File: spec/units/magic_variables_spec.rb [hunk 1]
```diff
@@ -22,6 +22,15 @@
         expect(magic_variables.fetch(:_prior)).to eq 'a-branch-name'
         expect(repo).to have_received(:revision_name).with('@{-1}')
       end
+
+      it 'raises when there is no prior branch' do
+        repo = double('GitRepository', revision_name: nil)
+        magic_variables = described_class.new(repo)
+
+        expect { magic_variables.fetch(:_prior) }.to raise_exception(
+          Gitsh::UnsetVariableError,
```
Comment (georgebrock) [inline spec/units/magic_variables_spec.rb]: We're asserting that sensible errors are output in the integration tests. I'm not sure there's much value in repeating them here.

File: lib/gitsh/magic_variables.rb [hunk 2]
```diff
@@ -21,15 +21,25 @@ def available_variables
     end
 
     def _prior
-      repo.revision_name('@{-1}')
+      repo.revision_name('@{-1}').tap do |revision|
+        if revision.nil?
+          raise UnsetVariableError, 'No prior branch'
+        end
```
Comment (georgebrock) [inline lib/gitsh/magic_variables.rb]: Good call. Done.

**Comment by georgebrock** [comment]
Thanks for the reviews.
